# Generated by Django 4.2.3 on 2023-09-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=100)),
                ('order_note', models.CharField(blank=True, max_length=100)),
                ('order_total', models.FloatField()),
                ('iva', models.FloatField()),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Nuevo', max_length=20)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPagos.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('id_carta', models.CharField(max_length=24)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPagos.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPagos.payment')),
            ],
        ),
    ]
