# Generated by Django 4.2.3 on 2023-09-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagos', '0002_remove_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
    ]
