# Generated by Django 4.2.3 on 2023-09-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagos', '0003_remove_order_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardorder',
            name='payment',
        ),
    ]
